### ISSUE TITLE
Uses / end goal

### ISSUE THREAD

**Issue by TomWFox** [parse-community/benchmark#2]
I'm interested to know more about how you think this could be used?
These are the things that come to mind...
- People wanting to see how efficient/how well Parse Server scales
- Running against PRs for Parse Server to check that they haven't caused performance issues
- Running against Parse Server master

something else completely? (I might be totally off base 😂)

**Comment by TomWFox** [comment]
@dplewis also could you add the core team to this repo...
<img width="1021" alt="Screenshot 2019-08-16 at 21 04 52" src="https://user-images.githubusercontent.com/13188249/63195056-7fd0cc00-c069-11e9-914b-57c70ff7391d.png">

**Comment by dplewis** [comment]
Done.

The main goal is to make benchmarking easier. The current go to solution is google how to benchmark.

Benchmarking per feature like push notification, large number of roles, etc and everything you mentioned.

**Comment by TomWFox** [comment]
Ok, good to know.

I think running against PRs would be awesome!
